/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttorneysRouteImport } from './routes/attorneys'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as NotableCasesRouteImport } from './routes/notable-cases'
import { Route as PracticeAreasRouteImport } from './routes/practice-areas'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as TestimonialsRouteImport } from './routes/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttorneysRoute = AttorneysRouteImport.update({
  id: '/attorneys',
  path: '/attorneys',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const NotableCasesRoute = NotableCasesRouteImport.update({
  id: '/notable-cases',
  path: '/notable-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasRoute = PracticeAreasRouteImport.update({
  id: '/practice-areas',
  path: '/practice-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attorneys': typeof AttorneysRoute
  '/consultation': typeof ConsultationRoute
  '/notable-cases': typeof NotableCasesRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/publications': typeof PublicationsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attorneys': typeof AttorneysRoute
  '/consultation': typeof ConsultationRoute
  '/notable-cases': typeof NotableCasesRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/publications': typeof PublicationsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attorneys': typeof AttorneysRoute
  '/consultation': typeof ConsultationRoute
  '/notable-cases': typeof NotableCasesRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/publications': typeof PublicationsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attorneys'
    | '/consultation'
    | '/notable-cases'
    | '/practice-areas'
    | '/publications'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attorneys'
    | '/consultation'
    | '/notable-cases'
    | '/practice-areas'
    | '/publications'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/attorneys'
    | '/consultation'
    | '/notable-cases'
    | '/practice-areas'
    | '/publications'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttorneysRoute: typeof AttorneysRoute
  ConsultationRoute: typeof ConsultationRoute
  NotableCasesRoute: typeof NotableCasesRoute
  PracticeAreasRoute: typeof PracticeAreasRoute
  PublicationsRoute: typeof PublicationsRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attorneys': {
      id: '/attorneys'
      path: '/attorneys'
      fullPath: '/attorneys'
      preLoaderRoute: typeof AttorneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notable-cases': {
      id: '/notable-cases'
      path: '/notable-cases'
      fullPath: '/notable-cases'
      preLoaderRoute: typeof NotableCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas': {
      id: '/practice-areas'
      path: '/practice-areas'
      fullPath: '/practice-areas'
      preLoaderRoute: typeof PracticeAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttorneysRoute: AttorneysRoute,
  ConsultationRoute: ConsultationRoute,
  NotableCasesRoute: NotableCasesRoute,
  PracticeAreasRoute: PracticeAreasRoute,
  PublicationsRoute: PublicationsRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
